create table Doctor (id bigint not null generated by default as identity (start with 1), name varchar(255) not null, patronymic varchar(255), lastName varchar(255) not null, specialization varchar(255) not null, primary key (id));
create table Patient (id bigint not null generated by default as identity (start with 1), name varchar(255) not null, patronymic varchar(255), lastName varchar(255) not null, phone_number varchar(255), primary key (id));
create table Recipe (id bigint not null generated by default as identity (start with 1), date date, description varchar(255), priority varchar(255), validity varchar(255), doctor_id bigint not null, patient_id bigint not null, primary key (id));
alter table Recipe add constraint FKDoctor foreign key (doctor_id) references Doctor;
alter table Recipe add constraint FKPatient foreign key (patient_id) references Patient;
